version: '3'
services:
  db:
    container_name: 'postgres'
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=reclamador
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    container_name: 'reclamador'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1

volumes:
  postgres_data: