# Generated by Django 4.2.2 on 2023-06-24 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import api.reclamaciones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha del vuelo')),
                ('fly_number', models.CharField(default='AB123', max_length=5, validators=[api.reclamaciones.models.validate_flight_number], verbose_name='Número de vuelo')),
                ('airline_name', models.CharField(default='undefined', max_length=100, verbose_name='Nombre de la aerolínea')),
                ('arrival_airport', models.CharField(default='000', max_length=3, validators=[api.reclamaciones.models.validate_airport_code], verbose_name='Aeropuerto de llegada')),
                ('departure_airport', models.CharField(default='000', max_length=3, validators=[api.reclamaciones.models.validate_airport_code], verbose_name='Aeropuerto de salida')),
                ('trial_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha vista')),
                ('file_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de expediente')),
                ('claimed_amount', models.FloatField(blank=True, null=True, verbose_name='Cantidad reclamada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Reclamacion',
                'verbose_name_plural': 'Reclamaciones',
            },
        ),
    ]
