# Generated by Django 4.2.2 on 2023-06-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacion',
            old_name='arrival_airport',
            new_name='aeropuerto_llegada',
        ),
        migrations.RenameField(
            model_name='reclamacion',
            old_name='departure_airport',
            new_name='aeropuerto_salia',
        ),
        migrations.RenameField(
            model_name='reclamacion',
            old_name='claimed_amount',
            new_name='cantidad_reclamada',
        ),
        migrations.RenameField(
            model_name='reclamacion',
            old_name='trial_date',
            new_name='fecha_vista',
        ),
        migrations.RenameField(
            model_name='reclamacion',
            old_name='fly_date',
            new_name='fecha_vuelo',
        ),
        migrations.RenameField(
            model_name='reclamacion',
            old_name='airline_name',
            new_name='nombre_aerolinea',
        ),
        migrations.RenameField(
            model_name='reclamacion',
            old_name='file_number',
            new_name='numero_expediente',
        ),
        migrations.RenameField(
            model_name='reclamacion',
            old_name='fly_number',
            new_name='numero_vuelo',
        ),
    ]
