# Generated by Django 4.2.2 on 2023-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0003_alter_reclamacion_numero_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='fecha_vuelo',
            field=models.DateTimeField(verbose_name='Fecha del vuelo'),
        ),
    ]
