# Generated by Django 4.2.2 on 2023-06-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0004_alter_reclamacion_fecha_vuelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacion',
            old_name='aeropuerto_salia',
            new_name='aeropuerto_salida',
        ),
    ]
